apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-deployment
  labels:
    app: blogapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp

  template:
    metadata:
      labels:
        app: blogapp

    spec:
      containers:
        - name: commentservice
          image: fredamoako/comment-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP

        - name: postservice
          image: fredamoako/post-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP

        - name: userservice
          image: fredamoako/user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              protocol: TCP

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
  labels:
    app: blogapp

spec:
  type: NodePort
  selector:
    app: blogapp

  ports:
    - protocol: TCP
      name: commentservice
      port: 8081
      targetPort: 80
      nodePort: 30001

    - protocol: TCP
      name: postservice
      port: 8082
      targetPort: 8082
      nodePort: 30002

    - protocol: TCP
      name: userservice
      port: 8083
      targetPort: 8083
      nodePort: 30003
